services:
  web:
    image: tomcat:11.0
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Rome
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./target/lupus-1.00.war:/usr/local/tomcat/webapps/lupus.war

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Europe/Rome
    volumes:
      - ./src/main/database:/docker-entrypoint-initdb.d/
      - ./data/db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 10s
      retries: 50

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"